export const LIVE_ACTIVITY_WINDOW_HOURS = 6
export const LIVE_ACTIVITY_WINDOW_MINUTES = LIVE_ACTIVITY_WINDOW_HOURS * 60
export const LIVE_ACTIVITY_WINDOW_LABEL = `${LIVE_ACTIVITY_WINDOW_HOURS} hours`
