import type { components } from './generated/api'

export type TokenUsage = components['schemas']['TokenUsage']
export type SummaryResponse = components['schemas']['SummaryResponse']
export type DailyUsage = components['schemas']['DailyUsage']
export type DailyResponse = components['schemas']['DailyResponse']
export type ModelUsage = components['schemas']['ModelUsage']
export type ModelsResponse = components['schemas']['ModelsResponse']
export type ProjectUsage = components['schemas']['ProjectUsage']
export type ProjectsResponse = components['schemas']['ProjectsResponse']
export type ProviderUsage = components['schemas']['ProviderUsage']
export type ProvidersResponse = components['schemas']['ProvidersResponse']
export type ProjectSessionUsage = components['schemas']['ProjectSessionUsage']
export type ProjectDetailResponse = components['schemas']['ProjectDetailResponse']
export type LiveSnapshotResponse = components['schemas']['LiveSnapshotResponse']
export type ModelDetailResponse = components['schemas']['ModelDetailResponse']
export type DateInsightsResponse = components['schemas']['DateInsightsResponse']
export type DataSourcePublic = components['schemas']['DataSourcePublic']
export type SourceRegistryPublic = components['schemas']['SourceRegistryPublic']
export type SourceHealth = components['schemas']['SourceHealth']
export type SourceFailure = Record<string, string>
